#!/usr/bin/env ruby
require_relative 'ship'

# проверка кол-ва корабликов по размерам
def check_count_ships(ships, size)
  ships.select{|s| s.ship_size == size}.size == Ship.how_many_ships(size)
end


size = 1
counter = 1 # Для отображения
ships = []
loop do 
  puts "Введите название #{counter}-го Кораблика"
  puts 'Для подтверждения нажмите ENTER'
  
  name1 = gets.chomp # получении наименования Кораблика
  
  begin
    ship = Ship.new(name1, size)
  rescue Exception => e
    puts e.message; next
  end
 
  puts "Введите координаты #{counter}-го Кораблика"
  
  
  loop do
    puts 'Формат ввода \'x y\' например \'1 12\''
    puts 'Имейте ввиду при не указании координаты, по умолчанию равна \'0\''
    coords = oords.scan(/\w+/).map(&:chomp)
    
    # Обработка исключения при добавлении  
    begin
      ship.add(coords[0], coords[1]) # Добавляем координату 
    rescue Exception => e
      puts e.message; next
    end
    break if ship.ready?
  end

  ships << ship

  break if size == 4
  size += 1 if check_count_ships(ships, size)
  counter += 1
end
puts "Кол-во корабликов #{ships.size}"
