#!/usr/bin/env ruby
require_relative 'worker'

list_workers = []

loop do
	puts 'Введите Имя работника:'
	worker = gets.chomp 
	break if worker == 'exit'
	puts 'Размер зарплаты работника:'
	salary = gets.chomp
	break if salary == 'exit'
	begin
	  worker = Worker.new(worker, salary)
	rescue Exception => e
	  puts e.message; next
	end

	list_workers << worker
end

list_workers.map(&:to_str).tap{ |x| puts x }
list_workers.map(&:to_ary).tap{ |x| p x } # Вывод массива как есть