#!/usr/bin/env ruby
require_relative 'shot'


puts 'Введите координаты X корабля'
puts 'Для подтверждения нажмите ENTER'
coords = gets
coords = coords.scan(/\w+/) 

coord = Shot.new(coords[0].chomp, coords[1].chomp)
p coord.coords
	